#!/usr/bin/env bash

# ietf-tools API docs at https://author-tools.ietf.org/doc/
API_ORIGIN="https://author-tools.ietf.org/api2" 

SRC="draft-peabody-dispatch-new-uuid-format-03.xml"

DST_HTML=${SRC/xml/html}
DST_TEXT==${SRC/xml/txt}

# Note: Passing referer circumvents the need for an API key
REFERER="Referer: https://author-tools.ietf.org/"

function usage() {
  echo "Usage: build [command]

Available commands:  
  lint - validate document
  html - render html format
  text - render text format
  all - lint (then render all formats)"
}

if ! test -f "${SRC}"; then
    echo "${SRC} not found"
    exit 1
fi


case $1 in 
  lint)
    if ! command -v jq &> /dev/null; then
      echo "\`jq\` command not found. See https://stedolan.github.io/jq/download/"
      exit 1
    fi

    results=$(curl -s -X POST -H "${REFERER}" -F "file=@${SRC}" "${API_ORIGIN}/validate")

    errors=$(echo $results | jq '.errors')
    if [[ $errors != "[]" ]]; then
      echo "Lint errors: $errors"
    fi

    warnings=$(echo $results | jq '.warnings')
    if [[ $warnings != "[]" ]]; then
      echo "Lint warnings: $warnings"
    fi

    if [[ $errors != "[]" || $warnings != "[]" ]]; then
      exit 1
    fi

    echo "No lint issues"
    ;;

  text)
    curl -s -X POST -H "${REFERER}" -F "file=@${SRC}" "${API_ORIGIN}/render/text" > ${DST_TEXT}
    ;;

  html)
    curl -s -X POST -H "${REFERER}" -F "file=@${SRC}" "${API_ORIGIN}/render/html" > ${DST_HTML}
    ;;

  all)
    build lint && build text && build html
    ;;

  *)
    usage
    ;;
esac
